version: '3.1'

services:
  app:
    build: .
    ports:
      - 10200:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dictcard
      POSTGRES_PASSWORD: dictcard
      POSTGRES_DB: dictcard
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./pgdata/:/var/lib/postgresql/data/pgdata"

  adminer:
    image: adminer
    restart: always
    ports:
      - 10100:8080